/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    SelectedNodesList: typeof import('./src/components/SelectedNodesList.vue')['default']
    TreeNode: typeof import('./src/components/TreeNode.vue')['default']
  }
}
